### ISSUE TITLE
Offenses Detected By RuboCop

### ISSUE THREAD

**Issue by KellyGithubID** [yegor256/hoc#24]
Offenses are detected by RuboCop, which leads to error messages when doing rake check

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this issue

**Comment by 0crat** [comment]
@kellygithubid[/z](https://www.0crat.com/u/kellygithubid) this project will fix the problem faster if you donate a few dollars to it; just [click here](https://www.0crat.com/contrib/C3RFVLU72) and pay via Stripe, it's very fast, convenient and appreciated; thanks a lot!

**Comment by yegor256** [comment]
@KellyGithubID I was wrong, polished and fixed in c627b6e

**Comment by 0crat** [comment]
Job `gh:yegor256/hoc#24` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
